package commands;

import controllers.OpeningHours_Controller;
import messages.Message;
import ocsf.server.ConnectionToClient;

/**
 * Command implementation for handling requests related to the restaurant's opening hours.
 * This class delegates the message processing to the OpeningHours_Controller.
 */
public class OpeningHoursCommand implements Command {
    
    /**
     * Executes the opening hours command by delegating the message to the relevant controller.
     * * @param msg    The message containing the opening hours request.
     * @param client The connection to the client that sent the request.
     * @return A Message object containing the response generated by OpeningHours_Controller.
     */
    @Override
    public Message execute(Message msg, ConnectionToClient client) {
        return OpeningHours_Controller.handle(msg);
    }
}