package commands;

import controllers.Table_Controller;
import messages.Message;
import ocsf.server.ConnectionToClient;

/**
 * Command implementation for managing restaurant table operations.
 * This class delegates table-related requests to the Table_Controller.
 */
public class TableCommand implements Command {
    
    /**
     * Executes the table management command by delegating the message to the relevant controller.
     * * @param msg    The message containing table-related data or requests.
     * @param client The connection to the client that sent the request.
     * @return A Message object containing the response generated by Table_Controller.
     */
    @Override
    public Message execute(Message msg, ConnectionToClient client) {
        return Table_Controller.handle(msg);
    }
}